import type { Teacher } from "./types";

export const TEACHERS: Teacher[] = [
  {
    id: "t-001",
    name: "Ustadh Ahmad Ali",
    gender: "male",
    subject: "Tajweed & Hifz",
    language: "English, Arabic",
    country: "Egypt",
    country_flag: "eg",
    experience_years: 10,
    price_per_class: 15,
    rating: 4.9,
    review_count: 134,
    bio: "I have been teaching Quran for over 10 years with a focus on Tajweed and Hifz programs. I hold an Ijazah in Quran recitation and have helped over 200 students worldwide complete their memorization goals.",
    teaching_style:
      "Patient, structured, and encouraging. I create a personalized plan for each student.",
    certifications: "Ijazah in Tajweed, Al-Azhar University Certified",
    intro_video_url: "",
    available_slots: ["Mon 9am UTC", "Wed 11am UTC", "Fri 4pm UTC", "Sat 10am UTC"],
    is_featured: true,
    slug: "ustadh-ahmad-ali",
  },
  {
    id: "t-002",
    name: "Sister Fatima Malik",
    gender: "female",
    subject: "Quran for Kids & Noorani Qaida",
    language: "English, Urdu",
    country: "Pakistan",
    country_flag: "pk",
    experience_years: 6,
    price_per_class: 12,
    rating: 4.8,
    review_count: 98,
    bio: "Specializing in teaching young children, I make Quran learning fun and engaging. My students love the interactive storytelling approach I use to teach Islamic values alongside recitation.",
    teaching_style:
      "Fun, engaging, and child-friendly. I use games and rewards to keep kids motivated.",
    certifications: "Diploma in Islamic Education, Certified Kids Quran Teacher",
    intro_video_url: "",
    available_slots: ["Tue 2pm UTC", "Thu 3pm UTC", "Sat 8am UTC", "Sun 10am UTC"],
    is_featured: true,
    slug: "sister-fatima-malik",
  },
  {
    id: "t-003",
    name: "Sheikh Omar Hassan",
    gender: "male",
    subject: "Arabic Language & Tafseer",
    language: "English, Arabic, French",
    country: "Jordan",
    country_flag: "jo",
    experience_years: 14,
    price_per_class: 20,
    rating: 5.0,
    review_count: 201,
    bio: "With 14 years of experience teaching classical Arabic and Tafseer, I help students go beyond recitation to truly understand the meaning of the Quran. I have students from over 15 countries.",
    teaching_style:
      "Academic yet accessible. I connect Quranic meanings to real life situations.",
    certifications:
      "Masters in Islamic Studies, Jordan University. Ijazah in Tafseer.",
    intro_video_url: "",
    available_slots: ["Mon 6pm UTC", "Wed 6pm UTC", "Thu 7pm UTC"],
    is_featured: true,
    slug: "sheikh-omar-hassan",
  },
  {
    id: "t-004",
    name: "Ustadha Maryam Yusuf",
    gender: "female",
    subject: "Female Students Only — Quran & Tajweed",
    language: "English, Malay",
    country: "Malaysia",
    country_flag: "my",
    experience_years: 7,
    price_per_class: 14,
    rating: 4.9,
    review_count: 87,
    bio: "I provide a safe and comfortable learning environment exclusively for female students and young girls. My approach is gentle, supportive, and rooted in traditional Islamic values.",
    teaching_style:
      "Warm, supportive, and confidence-building. Perfect for sisters new to Quran learning.",
    certifications:
      "Diploma in Quran Recitation, International Islamic University Malaysia",
    intro_video_url: "",
    available_slots: ["Tue 10am UTC", "Thu 11am UTC", "Sun 2pm UTC"],
    is_featured: false,
    slug: "ustadha-maryam-yusuf",
  },
  {
    id: "t-005",
    name: "Ustadh Bilal Qureshi",
    gender: "male",
    subject: "Hifz Program (Full Memorization)",
    language: "English, Urdu",
    country: "United Kingdom",
    country_flag: "gb",
    experience_years: 9,
    price_per_class: 18,
    rating: 4.8,
    review_count: 112,
    bio: "I run a structured 3-year Hifz program online. My students follow a proven daily revision system that ensures long-term retention. I have helped 40+ students complete their Hifz online.",
    teaching_style:
      "Disciplined and systematic. I track every student's daily progress closely.",
    certifications: "Hafiz ul Quran, Deobandi Ijazah",
    intro_video_url: "",
    available_slots: ["Mon 7am UTC", "Wed 7am UTC", "Fri 7am UTC", "Sat 6am UTC"],
    is_featured: false,
    slug: "ustadh-bilal-qureshi",
  },
  {
    id: "t-006",
    name: "Sister Aisha Rahman",
    gender: "female",
    subject: "Islamic Studies & Duas for Kids",
    language: "English",
    country: "United States",
    country_flag: "us",
    experience_years: 5,
    price_per_class: 13,
    rating: 4.7,
    review_count: 63,
    bio: "Born and raised in the US, I understand the challenges of raising Muslim kids in the West. My classes combine Quran recitation, daily duas, and fun Islamic stories tailored for children aged 4 to 12.",
    teaching_style:
      "Creative, storytelling-based, and highly interactive. Parents love seeing their kids excited about Islam.",
    certifications: "Bachelor of Islamic Studies, Islamic Online University",
    intro_video_url: "",
    available_slots: ["Mon 4pm UTC", "Wed 4pm UTC", "Sat 3pm UTC"],
    is_featured: false,
    slug: "sister-aisha-rahman",
  },
  {
    id: "t-007",
    name: "Ustadh Yusuf Al-Turki",
    gender: "male",
    subject: "Tajweed Mastery — Advanced Level",
    language: "English, Arabic, Turkish",
    country: "Turkey",
    country_flag: "tr",
    experience_years: 12,
    price_per_class: 22,
    rating: 4.9,
    review_count: 155,
    bio: "I specialize in advanced Tajweed for students who already read Quran and want to perfect their recitation. My students have gone on to lead prayers at their local mosques worldwide.",
    teaching_style:
      "Precise, detail-oriented, and highly motivating. I push students to excellence.",
    certifications: "Ijazah with Sanad, Diyanet Certified Turkey",
    intro_video_url: "",
    available_slots: ["Tue 8am UTC", "Thu 9am UTC", "Sat 11am UTC"],
    is_featured: true,
    slug: "ustadh-yusuf-al-turki",
  },
  {
    id: "t-008",
    name: "Ustadha Khadijah Osei",
    gender: "female",
    subject: "Quran for Reverts & Beginners",
    language: "English",
    country: "Ghana",
    country_flag: "gh",
    experience_years: 4,
    price_per_class: 10,
    rating: 4.8,
    review_count: 44,
    bio: "Being a revert myself, I have a deep understanding of where new Muslims start from. I teach absolute beginners with zero prior knowledge — starting from Arabic letters all the way to fluent Quran recitation.",
    teaching_style:
      "Compassionate, zero-judgment, and beginner-friendly. Perfect for reverts and adult beginners.",
    certifications: "Certified Quran Teacher, Al-Maghrib Institute",
    intro_video_url: "",
    available_slots: ["Mon 2pm UTC", "Fri 3pm UTC", "Sun 4pm UTC"],
    is_featured: false,
    slug: "ustadha-khadijah-osei",
  },
];

export function getSeedTeacherBySlug(slug: string): Teacher | undefined {
  return TEACHERS.find((t) => t.slug === slug);
}
